import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{MapContainer,TileLayer,Marker,Tooltip,Circle,useMap}from'react-leaflet';
import L from'leaflet';
import'leaflet/dist/leaflet.css';import'./styles.css';
import{getMarineData,refreshMarineData}from'./services/marineDataService';

const DEFAULT={dark:false,alerts:true,location:false,language:'ko',autoRefresh:true,dataSaver:false,layers:{markers:true,names:true,risk:true,rip:true,jelly:true,wave:true,surf:true}};
const copy={ko:{home:'홈',risk:'위험도',settings:'설정',details:'상세정보 보기',back:'뒤로',safe:'관심',caution:'주의',alert:'경계',danger:'위험',favorite:'즐겨찾기',nearest:'가까운 해수욕장',current:'현재 상태',updated:'최근 갱신',noFavorites:'등록된 즐겨찾기가 없습니다.',language:'언어 / Language'},en:{home:'Home',risk:'Risk',settings:'Settings',details:'View details',back:'Back',safe:'Low',caution:'Caution',alert:'Warning',danger:'Danger',favorite:'Favorite',nearest:'Nearest beach',current:'Current status',updated:'Updated',noFavorites:'No saved favorites.',language:'Language'}};
const safeRead=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}};
const safeSave=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const grade=n=>n>=78?'danger':n>=55?'alert':n>=30?'caution':'safe';
const color=g=>({safe:'#149a72',caution:'#d59d18',alert:'#e67723',danger:'#da4751'}[g]);
const risk=b=>Math.round(b.rip*.5+Math.min(100,b.jelly/12)*.28+Math.min(100,b.wave*65)*.22);
function surf(b){let score=Math.round((b.wave<.35?32:b.wave<.8?78:b.wave<1.3?62:35)*.65+(100-b.rip)*.35);if(b.rip>=70)score=0;else if(b.rip>=55)score=Math.min(30,score);else if(b.rip>=30)score=Math.min(65,score);return{score,status:score===0?'이용 금지':score>=70?'좋음':score>=45?'보통':'주의'}}
const jelly=b=>b.jellyPrevious?Math.round((b.jelly-b.jellyPrevious)/b.jellyPrevious*100):null;
const icon=g=>L.divIcon({className:'marker-wrap',html:`<span class="map-pin ${g}"><b>✓</b></span>`,iconSize:[32,38],iconAnchor:[16,36]});
function Recenter({beach}){const map=useMap();useEffect(()=>{if(beach)map.flyTo(beach.center,14,{duration:.55})},[beach,map]);return null}
function Legend({small=false}){return <div className={small?'legend compact':'legend'}>{[['safe','관심 또는 안전','현재 위험 가능성이 낮은 상태'],['caution','주의','현장 상황을 확인해야 하는 상태'],['alert','경계','입수나 활동을 자제해야 하는 상태'],['danger','위험','입수와 해양활동을 중단해야 하는 상태']].map(([g,n,d])=><div key={g}><i className={g}/><span><b>{n}</b><small>{d}</small></span></div>)}</div>}
function SafetyMap({beaches,selected,onSelect,layers,detail=false}){const[legend,setLegend]=useState(false);return <div className={'map-shell '+(detail?'detail-map':'')}><MapContainer center={selected?.center||[35.15,129.12]} zoom={detail?14:11} className="map" scrollWheelZoom><Recenter beach={selected}/><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution="© OpenStreetMap contributors"/>{beaches.map(b=>{const r=risk(b),s=surf(b),g=grade(r);return <React.Fragment key={b.id}>{layers.risk&&<Circle center={b.riskCenter} radius={b.radius} interactive={false} pathOptions={{color:color(g),fillColor:color(g),fillOpacity:.25,weight:1.5}}/>}{layers.markers&&<Marker position={b.center} icon={icon(g)} eventHandlers={{click:()=>onSelect?.(b)}}>{layers.names&&<Tooltip permanent direction="bottom" offset={[0,10]} className="beach-label" interactive eventHandlers={{click:()=>onSelect?.(b)}}>{b.shortName}</Tooltip>}</Marker>}{layers.rip&&<Circle center={[b.riskCenter[0]-.00035,b.riskCenter[1]]} radius={22} interactive={false} pathOptions={{color:'#075f8d',fillColor:'#087fb7',fillOpacity:.8,weight:1}}/>}{layers.jelly&&<Circle center={[b.riskCenter[0],b.riskCenter[1]+.00042]} radius={18} interactive={false} pathOptions={{color:'#7b55c7',fillColor:'#7b55c7',fillOpacity:.8,weight:1}}/>}{layers.wave&&<Circle center={[b.riskCenter[0]+.00032,b.riskCenter[1]]} radius={16} interactive={false} pathOptions={{color:'#1a9ab5',fillColor:'#1a9ab5',fillOpacity:.8,weight:1}}/>}{layers.surf&&<Circle center={[b.riskCenter[0],b.riskCenter[1]-.0004]} radius={16} interactive={false} pathOptions={{color:s.score===0?'#da4751':'#149a72',fillColor:s.score===0?'#da4751':'#149a72',fillOpacity:.8,weight:1}}/>}</React.Fragment>})}</MapContainer><div className="map-key"><button onClick={()=>setLegend(v=>!v)} aria-expanded={legend}>위험도 범례</button>{legend&&<Legend/>}</div></div>}
function Badge({score,t}){const g=grade(score);return <span className={'badge '+g}><i/>{t[g]} · {score}점</span>}
function Star({beach,favorites,toggle}){const on=favorites.includes(beach.id);return <button className={'star '+(on?'on':'')} onClick={()=>toggle(beach.id)} aria-label="즐겨찾기">{on?'★':'☆'}</button>}
function Metric({title,value,detail}){return <div className="metric"><small>{title}</small><b>{value}</b><span>{detail}</span></div>}
function Header({t,data}){return <><header><div className="brand"><span className="logo">⌖</span><div><small>BUSAN OCEAN SAFETY</small><h1>해담</h1></div></div><div className="head-state">부산 바다 안전</div></header><div className="updated">기준 시각 · {data[0].updatedAt} · {t.updated}</div></>}
function Summary({beach,t,favorites,toggle,onDetail}){const score=risk(beach),s=surf(beach),j=jelly(beach);return <section className="card summary"><div className="row"><div><small>{beach.area}</small><h2>{beach.name}</h2></div><Badge score={score} t={t}/><Star beach={beach} favorites={favorites} toggle={toggle}/></div><div className="metrics"><Metric title="현재 이안류 단계" value={`S=${beach.rip}`} detail={t[grade(beach.rip)]}/><Metric title="해파리 출현 추세" value={j===null?'신규 출현':`${j>0?'+':''}${j}%`} detail={beach.jellyAlert}/><Metric title="현재 파고" value={`${beach.wave.toFixed(1)}m`} detail={`수온 ${beach.temperature.toFixed(1)}℃`}/><Metric title="현재 서핑 지수" value={`${s.score}점`} detail={s.status}/></div><button className="primary" onClick={()=>onDetail(beach)}>{t.details}</button></section>}
function Notices({data}){const messages=data.filter(b=>b.rip>=55||b.jellyAlert==='특보'||surf(b).score===0).map(b=>b.jellyAlert==='특보'?`${b.shortName} 해파리 특보`:surf(b).score===0?`${b.shortName} 서핑 이용 금지`:`${b.shortName} 이안류 ${grade(b.rip)==='danger'?'위험':'경계'}`);return messages.length?<div className="notice">⚠ <span>{messages.slice(0,2).join(' · ')}</span></div>:null}
function Home(p){const[selected,setSelected]=useState(p.data[0]);const nearest=()=>{if(!p.settings.location){p.toast('설정에서 위치정보 사용을 켜면 가까운 해수욕장을 추천합니다.');return}if(!navigator.geolocation){p.toast('이 기기에서는 위치정보를 사용할 수 없습니다.');return}navigator.geolocation.getCurrentPosition(pos=>{const n=p.data.reduce((a,b)=>Math.hypot(a.center[0]-pos.coords.latitude,a.center[1]-pos.coords.longitude)<Math.hypot(b.center[0]-pos.coords.latitude,b.center[1]-pos.coords.longitude)?a:b);setSelected(n);p.toast(`${n.name}을(를) 추천합니다.`)},()=>p.toast('위치 권한이 허용되지 않았습니다. 다른 기능은 정상적으로 사용할 수 있습니다.'))};return <main className="page"><Header t={p.t} data={p.data}/>{p.settings.alerts&&<Notices data={p.data}/>}<section className="intro"><div><small>오늘의 부산 바다</small><h2>{selected.name}</h2><p>바다 상태와 안전정보를 한눈에 확인하세요.</p></div><button className="secondary" onClick={nearest}>⌖ {p.t.nearest}</button></section><SafetyMap beaches={p.data} selected={selected} onSelect={setSelected} layers={p.settings.layers}/><Summary beach={selected} {...p} onDetail={p.open}/></main>}
function RiskPage(p){const ordered=useMemo(()=>[...p.data].sort((a,b)=>risk(b)-risk(a)),[p.data]);return <main className="page"><Header t={p.t} data={p.data}/><section className="intro title"><div><small>BEACH RISK RANKING</small><h2>해수욕장 위험도</h2><p>이안류, 해파리 증가, 파고를 반영한 종합 위험도입니다.</p></div></section><div className="list">{ordered.map((b,i)=><article className="card rank" key={b.id}><div className="row"><em>{i+1}</em><div><h3>{b.name}</h3><small>{b.area}</small></div><Badge score={risk(b)} t={p.t}/><Star beach={b} favorites={p.favorites} toggle={p.toggle}/></div><div className="metrics"><Metric title="이안류" value={`S=${b.rip}`} detail={p.t[grade(b.rip)]}/><Metric title="해파리" value={jelly(b)===null?'신규':`${jelly(b)>0?'+':''}${jelly(b)}%`} detail={b.jellyAlert}/><Metric title="파고" value={`${b.wave}m`} detail={`수온 ${b.temperature}℃`}/><Metric title="서핑" value={`${surf(b).score}점`} detail={surf(b).status}/></div><button className="primary" onClick={()=>p.open(b)}>{p.t.details}</button></article>)}</div></main>}
function Detail(p){const b=p.beach,s=surf(b),j=jelly(b);return <main className="detail-page"><div className="detail-header"><button className="back" onClick={p.back}>← <span>{p.t.back}</span></button><div><small>BEACH DETAIL</small><h2>{b.name}</h2></div><Star beach={b} favorites={p.favorites} toggle={p.toggle}/></div><section className="detail-lead"><Badge score={risk(b)} t={p.t}/><p>현재 상태는 이안류, 최근 해파리 출현 추세, 파고와 서핑 지수를 함께 보여줍니다.</p></section><SafetyMap beaches={[b]} selected={b} layers={p.settings.layers} detail/><div className="detail-content"><Info title="이안류" icon="↝"><div className="two"><Metric title="현재 이안류 단계" value={`S=${b.rip}`} detail={p.t[grade(b.rip)]}/><Metric title="기준 시각" value={b.updatedAt} detail="현재 상태"/></div><p>{b.rip>=55?'강한 이안류 가능성이 있습니다. 입수와 해양 활동을 자제하고 현장 통제를 확인하세요.':'이안류 발생 가능성이 낮거나 보통입니다. 입수 전 현장 안전 안내를 확인하세요.'}</p></Info><Info title="최근 해파리 출현 추세" icon="◌"><div className="three"><Metric title="종류" value={b.species} detail={`알림 ${b.jellyAlert}`}/><Metric title="최근 변화" value={j===null?'신규 출현':`${j>0?'+':''}${j}%`} detail="최근 4주 추세"/><Metric title="관측 수" value={`${b.jelly}`} detail="현재 상태"/></div><div className="chart">{b.weekly.map((v,i)=><i key={i} style={{height:`${Math.min(100,Math.max(12,v/2))}%`}}/>)}</div></Info><Info title="파고와 수온" icon="≈"><div className="two"><Metric title="현재 파고" value={`${b.wave.toFixed(1)}m`} detail="현재 상태"/><Metric title="수온" value={`${b.temperature.toFixed(1)}℃`} detail={b.updatedAt}/></div></Info><Info title="서핑 지수" icon="⌁"><div className="two"><Metric title="현재 서핑 지수" value={`${s.score}점`} detail={s.status}/><Metric title="계산 기준" value={`S=${b.rip} · ${b.wave}m`} detail="파고 65% · 이안류 35%"/></div><p>{s.score===0?'현재 서핑 이용을 중단해야 합니다.':s.score>=60?'안전요원의 안내와 현장 여건을 확인한 뒤 이용하세요.':'보수적으로 판단하고 입수를 미루는 것을 권합니다.'}</p></Info><Info title="안전 행동 요령" icon="✓"><p>이안류에 휩쓸리면 해안과 평행한 방향으로 이동하고, 무리하지 말고 구조를 요청하세요. 긴급 상황은 119로 신고하세요.</p></Info></div></main>}
function Info({title,icon,children}){return <article className="card info"><h3><i>{icon}</i>{title}</h3>{children}</article>}
function Toggle({value,onChange}){return <button className={'toggle '+(value?'on':'')} onClick={()=>onChange(!value)} aria-label="설정 전환"><i/></button>}
function Setting({title,text,value,onChange}){return <div className="setting"><div><b>{title}</b><small>{text}</small></div><Toggle value={value} onChange={onChange}/></div>}
function Settings(p){const set=(k,v)=>p.setSettings({...p.settings,[k]:v});const layerNames={markers:'해수욕장 마커',names:'해수욕장 이름',risk:'위험 표시 원',rip:'이안류 상태',jelly:'해파리 상태',wave:'파고 상태',surf:'서핑 지수 상태'};return <main className="page"><Header t={p.t} data={p.data}/><section className="intro title"><div><small>PREFERENCES</small><h2>{p.t.settings}</h2><p>이 기기에서 안전정보를 편하게 확인하도록 설정합니다.</p></div></section><section className="card settings"><Setting title="다크 모드" text="모든 화면의 색상 테마를 전환합니다." value={p.settings.dark} onChange={v=>set('dark',v)}/><section className="fav-manager"><b>즐겨찾기 관리</b><small>항목을 누르면 상세정보를 볼 수 있습니다.</small><div>{p.favorites.length?p.favorites.map(id=>{const b=p.data.find(x=>x.id===id);return <button key={id} onClick={()=>p.open(b)}>{b.name}<span onClick={e=>{e.stopPropagation();p.toggle(id)}}>×</span></button>}):<small>{p.t.noFavorites}</small>}</div></section><Setting title="위험 알림" text="위험 상승, 특보, 높은 파고와 서핑 이용 금지를 배너로 표시합니다." value={p.settings.alerts} onChange={v=>set('alerts',v)}/><Setting title="위치정보 사용" text="허용하면 현재 위치에서 가까운 부산 해수욕장을 추천합니다." value={p.settings.location} onChange={v=>set('location',v)}/><div className="setting"><div><b>{p.t.language}</b><small>하단 탭과 주요 안내문을 전환합니다.</small></div><select value={p.settings.language} onChange={e=>set('language',e.target.value)}><option value="ko">한국어</option><option value="en">English</option></select></div><div className="setting stack"><div><b>지도 레이어 설정</b><small>지도에서 보여줄 요소를 선택합니다.</small></div><div className="layers">{Object.entries(layerNames).map(([k,n])=><label key={k}>{n}<Toggle value={p.settings.layers[k]} onChange={v=>set('layers',{...p.settings.layers,[k]:v})}/></label>)}</div></div><Setting title="자동갱신" text="현재 상태를 일정 간격으로 갱신합니다." value={p.settings.autoRefresh} onChange={v=>set('autoRefresh',v)}/><Setting title="데이터 절약 모드" text="자동갱신 간격을 늘려 사용량을 줄입니다." value={p.settings.dataSaver} onChange={v=>set('dataSaver',v)}/><details><summary>위험도 색상 안내</summary><Legend small/></details><details><summary>서핑 지수 계산 기준</summary><p>파고 적합도 65%와 이안류 안전도 35%를 반영합니다. 이안류 S 70 이상은 이용 금지, S 55 이상은 최대 30점으로 제한합니다.</p></details><button className="setting action" onClick={()=>p.toast('캐시를 새로고침했습니다.')}><div><b>캐시 새로고침</b><small>화면의 현재 상태를 다시 불러옵니다.</small></div><span>↻</span></button><button className="setting action reset" onClick={p.reset}><div><b>설정 초기화</b><small>모든 개인 설정을 기본값으로 되돌립니다.</small></div><span>↺</span></button><div className="app-info"><b>해담</b><small>부산 바다의 해양 환경과 안전정보를 한곳에 담습니다.</small></div></section></main>}
function Tabs({tab,setTab,t}){return <nav className="tabs">{[['home','⌂'],['risk','◉'],['settings','⚙']].map(([id,ic])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{ic}</span>{t[id]}</button>)}</nav>}
function App(){const saved=safeRead('haedam.settings',{});const[settings,setSettings]=useState({...DEFAULT,...saved,layers:{...DEFAULT.layers,...saved.layers}});const[favorites,setFavorites]=useState(()=>safeRead('haedam.favorites',[]));const[tab,setTab]=useState(()=>safeRead('haedam.tab','home'));const[detail,setDetail]=useState(null);const[data,setData]=useState(getMarineData);const[toast,setToast]=useState('');const t=copy[settings.language]||copy.ko;useEffect(()=>{document.body.classList.toggle('dark',settings.dark);safeSave('haedam.settings',settings)},[settings]);useEffect(()=>safeSave('haedam.favorites',favorites),[favorites]);useEffect(()=>safeSave('haedam.tab',tab),[tab]);useEffect(()=>{if(!settings.autoRefresh)return;const id=setInterval(()=>setData(d=>refreshMarineData(d)),settings.dataSaver?90000:30000);return()=>clearInterval(id)},[settings.autoRefresh,settings.dataSaver]);const toggle=id=>setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]);const notify=m=>{setToast(m);window.setTimeout(()=>setToast(''),4500)};const reset=()=>{if(window.confirm('모든 설정과 즐겨찾기를 초기화할까요?')){setSettings(DEFAULT);setFavorites([]);localStorage.removeItem('haedam.settings');localStorage.removeItem('haedam.favorites');notify('설정을 초기화했습니다.')}};const p={data,t,settings,setSettings,favorites,toggle,open:setDetail,toast:notify};return <>{toast&&<div className="toast">{toast}<button onClick={()=>setToast('')}>×</button></div>}{detail?<Detail {...p} beach={detail} back={()=>setDetail(null)}/>:<div className="shell">{tab==='home'?<Home {...p}/>:tab==='risk'?<RiskPage {...p}/>:<Settings {...p} reset={reset}/>}<Tabs tab={tab} setTab={setTab} t={t}/></div>}</>}
createRoot(document.getElementById('root')).render(<App/>);
