import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Circle, MapContainer, Marker, TileLayer, Tooltip, useMap} from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import './styles.css';
import {getMarineData, refreshMarineData} from './services/marineDataService';
import {calculateSurfingIndex} from './utils/calculateSurfingIndex';

const C={safe:'#168b6a',caution:'#d59b19',warning:'#e46f27',danger:'#d6444d'};
const defaults={dark:false,alerts:true,location:false,language:'ko',skill:'beginner',autoRefresh:true,layers:{markers:true,names:true,risk:true,rip:true,jelly:true,wave:true,surf:true}};
const copy={ko:{home:'홈',risk:'위험도',settings:'설정',detail:'상세정보 보기',back:'뒤로',updated:'최근 갱신',favorite:'즐겨찾기',nearest:'가까운 해수욕장',legend:'범례'},en:{home:'Home',risk:'Risk',settings:'Settings',detail:'View details',back:'Back',updated:'Updated',favorite:'Favorite',nearest:'Nearest beach',legend:'Legend'}};
const levels={safe:['관심','Safe'],caution:['주의','Caution'],warning:['경계','Warning'],danger:['위험','Danger']};
const surfEn={'매우 좋음':'Excellent','좋음':'Good','보통':'Fair','나쁨':'Poor','매우 나쁨':'Very poor'};
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const store=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
const rip=n=>n>=80?'danger':n>=55?'warning':n>=30?'caution':'safe';
const overall=b=>Math.round(Math.min(100,b.rip*.56+Math.min(100,b.jelly/12)*.27+Math.min(100,b.wave*60)*.17));
const risk=b=>rip(overall(b));
const jelly=b=>b.jellyPrevious===0?(b.jelly?'신규 출현':'변화 없음'):`${b.jelly>=b.jellyPrevious?'증가':'감소'} ${Math.abs(Math.round((b.jelly-b.jellyPrevious)/b.jellyPrevious*100))}%`;
const pin=(level,active)=>L.divIcon({className:'pin-shell',html:`<div class="pin ${level} ${active?'active':''}">⌖</div>`,iconSize:[34,42],iconAnchor:[17,40]});

function MapFocus({beach}){const map=useMap();useEffect(()=>{if(beach)map.flyTo(beach.center,14,{duration:.55})},[beach,map]);return null}
function Pill({beach,lang}){const x=risk(beach);return <span className={`pill ${x}`}><i/> {levels[x][lang==='en'?1:0]} · {overall(beach)}</span>}
function Fav({beach,favorites,toggle,label}){const on=favorites.includes(beach.id);return <button className={`fav ${on?'on':''}`} aria-label={label} onClick={()=>toggle(beach.id)}>{on?'★':'☆'}</button>}
function Field({label,value,sub}){return <div className="field"><small>{label}</small><strong>{value}</strong>{sub&&<span>{sub}</span>}</div>}
function MapLegend({lang}){return <div className="legend-card"><p><b>⌖ 해수욕장 마커</b> 대표 위치와 종합위험도를 나타냅니다.</p><p><b>● 색상 원</b> 바다에서 주의가 필요한 구역입니다.</p>{Object.keys(C).map(x=><div className="legend-row" key={x}><i className={x}/><span><b>{levels[x][lang==='en'?1:0]}</b><small>{x==='safe'?'일반 안전수칙을 지켜 이용하세요.':x==='caution'?'입수 전 현장 안내를 확인하세요.':x==='warning'?'수영과 해양활동을 자제하세요.':'입수와 해양활동을 중단하세요.'}</small></span></div>)}</div>}
function SafetyMap({data,selected,onSelect,layers,lang,detail=false}){const [open,setOpen]=useState(false);return <div className={`map-wrap ${detail?'detail-map':''}`}><MapContainer center={selected?.center||[35.16,129.12]} zoom={detail?14:11} className="map" scrollWheelZoom><MapFocus beach={selected}/><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution="© OpenStreetMap contributors"/>{data.map(b=>{const x=risk(b);return <React.Fragment key={b.id}>{layers.risk&&<Circle center={b.riskCenter} radius={b.radius} interactive={false} pathOptions={{color:C[x],weight:1.5,opacity:.85,fillColor:C[x],fillOpacity:.25}}/>}{layers.markers&&<Marker position={b.center} icon={pin(x,selected?.id===b.id)} eventHandlers={{click:()=>onSelect?.(b)}}>{layers.names&&<Tooltip permanent interactive direction="bottom" offset={[0,9]} className="beach-label">{b.shortName}</Tooltip>}</Marker>}</React.Fragment>})}</MapContainer><div className="legend-control"><button onClick={()=>setOpen(!open)}>{lang==='en'?'Legend':'범례'}</button>{open&&<MapLegend lang={lang}/>}</div></div>}
function Header({t,data}){return <><header><div className="brand"><span>◈</span><div><small>BUSAN OCEAN SAFETY</small><h1>해담</h1></div></div><div className="weather"><b>☀ 맑음</b><span>27°C</span></div></header><p className="updated">2026년 8월 5일 · 10:00 &nbsp;|&nbsp; {t.updated} {data[0].updatedAt}</p></>}
function Summary({beach,p}){const s=calculateSurfingIndex(beach,p.settings.skill);return <section className="card summary"><div className="card-top"><div><small>{beach.area}</small><h2>{beach.name}</h2></div><Pill beach={beach} lang={p.lang}/><Fav beach={beach} favorites={p.favorites} toggle={p.toggle} label={p.t.favorite}/></div><div className="metric-grid"><Field label="현재 이안류 단계" value={`S=${beach.rip}`} sub={levels[rip(beach.rip)][p.lang==='en'?1:0]}/><Field label="최근 해파리 출현 추세" value={jelly(beach)} sub={beach.jellyAlert}/><Field label="현재 파고" value={`${beach.wave.toFixed(1)}m`} sub={`수온 ${beach.temperature.toFixed(1)}°C`}/><Field label="현재 서핑 지수" value={`${s.score}점`} sub={p.lang==='en'?surfEn[s.status]:s.status}/></div><button className="primary" onClick={()=>p.open(beach)}>{p.t.detail} →</button></section>}
function Home(p){const [selected,setSelected]=useState(p.data[0]);const alerts=p.data.filter(b=>b.rip>=55||b.jellyAlert==='주의보'||b.control==='입수 금지');const near=()=>{if(!p.settings.location)return p.toast('설정에서 위치정보 사용을 켜면 가까운 해수욕장을 추천합니다.');navigator.geolocation?.getCurrentPosition(pos=>{const n=[...p.data].sort((a,b)=>Math.hypot(a.center[0]-pos.coords.latitude,a.center[1]-pos.coords.longitude)-Math.hypot(b.center[0]-pos.coords.latitude,b.center[1]-pos.coords.longitude))[0];setSelected(n);p.toast(`${n.name}을(를) 추천합니다.`)},()=>p.toast('위치 권한이 없어도 다른 기능은 정상 이용할 수 있습니다.'))};return <main className="page"><Header t={p.t} data={p.data}/>{p.settings.alerts&&alerts.length>0&&<div className="alert">⚠ <b>안전 알림</b> {alerts.map(b=>`${b.shortName} ${b.rip>=55?'이안류 '+levels[rip(b.rip)][0]:b.jellyAlert}`).join(' · ')}</div>}<section className="hero"><div><small>오늘의 부산 바다</small><h2>{selected.name}</h2><p>바다 상태와 안전정보를 한눈에 확인하세요.</p></div><button className="outline" onClick={near}>⌖ {p.t.nearest}</button></section><SafetyMap data={p.data} selected={selected} onSelect={setSelected} layers={p.settings.layers} lang={p.lang}/><Summary beach={selected} p={p}/></main>}
function RiskPage(p){const list=useMemo(()=>[...p.data].sort((a,b)=>overall(b)-overall(a)),[p.data]);return <main className="page"><Header t={p.t} data={p.data}/><section className="hero"><div><small>BEACH RISK RANKING</small><h2>해수욕장 위험도</h2><p>이안류, 해파리 증가, 파고, 서핑 상태를 종합한 현재 상태입니다.</p></div></section><div className="risk-list">{list.map((b,i)=>{const s=calculateSurfingIndex(b,p.settings.skill);return <article className="card risk-card" key={b.id}><div className="card-top"><em>{i+1}</em><div><h3>{b.name}</h3><small>{b.area}</small></div><Pill beach={b} lang={p.lang}/><Fav beach={b} favorites={p.favorites} toggle={p.toggle} label={p.t.favorite}/></div><div className="metric-grid"><Field label="이안류" value={`S=${b.rip}`} sub={levels[rip(b.rip)][0]}/><Field label="해파리" value={jelly(b)} sub={b.jellyAlert}/><Field label="현재 파고" value={`${b.wave}m`} sub={`수온 ${b.temperature}°C`}/><Field label="서핑" value={s.status} sub={`${s.score}점`}/></div><button className="primary" onClick={()=>p.open(b)}>{p.t.detail} →</button></article>})}</div></main>}
function Info({icon,title,children}){return <article className="card info"><h3><i>{icon}</i>{title}</h3>{children}</article>}
function Detail(p){const b=p.beach,s=calculateSurfingIndex(b,p.settings.skill),x=rip(b.rip);return <main className="detail-page"><div className="detail-head"><button className="back" onClick={p.back}>← <span>{p.t.back}</span></button><div><small>BEACH DETAIL</small><h2>{b.name}</h2></div><Fav beach={b} favorites={p.favorites} toggle={p.toggle} label={p.t.favorite}/></div><div className="detail-intro"><Pill beach={b} lang={p.lang}/><p>현장 안전요원과 입수 통제 안내를 우선 확인하세요.</p></div><SafetyMap data={[b]} selected={b} layers={p.settings.layers} lang={p.lang} detail/><div className="detail-content"><Info icon="≈" title="이안류"><div className="two-grid"><Field label="현재 이안류 지수" value={`S=${b.rip}`} sub={levels[x][0]}/><Field label="행동요령" value={b.rip>=55?'입수 자제':'현장 안내 확인'} sub="기준 시각"/></div><p>{b.rip>=55?'강한 이안류가 발생할 수 있습니다. 수영 실력과 관계없이 입수를 자제하세요.':'입수 전 현장 안내와 통제 여부를 확인하세요.'}</p></Info><Info icon="♧" title="최근 해파리 출현 추세"><div className="three-grid"><Field label="해파리 종류" value={b.species} sub={b.jellyAlert}/><Field label="최근 / 이전" value={`${b.jelly} / ${b.jellyPrevious}마리`} sub={jelly(b)}/><Field label="발견률" value={`${Math.min(70,Math.round(b.jelly/18))}%`} sub="기준 시각"/></div><div className="chart">{b.weekly.map((n,i)=><i key={i} style={{height:`${Math.max(8,Math.min(96,n/13))}%`}}/>)}</div><small>최근 4주 변화 그래프</small></Info><Info icon="≋" title="현재 파고와 수온"><div className="two-grid"><Field label="현재 파고" value={`${b.wave.toFixed(1)}m`} sub={b.waveDirection}/><Field label="수온" value={`${b.temperature.toFixed(1)}°C`} sub={b.wind}/></div></Info><Info icon="⌇" title="서핑 지수"><div className="three-grid"><Field label="현재 상태" value={s.status} sub={`${s.score}점`}/><Field label="선택 숙련도" value={p.skillName} sub={`권장 파고 ${s.range}`}/><Field label="입수 상태" value={b.control} sub="이안류 우선 적용"/></div><p>{s.reason}</p></Info><Info icon="i" title="안전 안내"><p>지도에 표시되는 반투명 색상 원은 시설물이나 구멍이 아니라 바다에서 특별히 주의하거나 피해야 하는 구역입니다. 원 밖이 반드시 안전하다는 뜻은 아닙니다.</p></Info></div></main>}
function Toggle({value,onChange}){return <button className={`toggle ${value?'on':''}`} aria-pressed={value} onClick={()=>onChange(!value)}><i/></button>}
function Setting({title,copy,children}){return <div className="setting"><div><b>{title}</b><small>{copy}</small></div>{children}</div>}
function Guide(){return <><div className="color-guide">{Object.keys(C).map(x=><div key={x}><i className={x}/><span><b>{levels[x][0]} · {x==='safe'?'관심 또는 안전':levels[x][0]}</b><small>{x==='safe'?'현재 위험 가능성이 낮은 상태입니다.':x==='caution'?'입수 전 현장 안내와 통제를 확인하세요.':x==='warning'?'수영과 해양활동을 자제하세요.':'입수와 해양활동을 중단하세요.'}</small></span></div>)}</div><div className="guide-copy"><h4>지도 위험 원의 의미</h4><p>지도에 표시되는 반투명 색상 원은 바다에서 특별히 주의하거나 피해야 하는 구역을 나타냅니다.</p><ul><li>원 위치: 위험이 예상되거나 주의가 필요한 바다 구역</li><li>원 범위: 이용자가 주의하거나 피해야 하는 바다 영역</li><li>원 색상: 해당 구역의 위험 단계</li><li>원 전체: 특별히 주의가 필요한 구역</li><li>원 중심: 별도의 특별한 의미가 없음</li></ul><p><b>원 밖의 구역이 반드시 안전하다는 뜻은 아닙니다.</b> 현장 안전요원, 입수 통제와 안내방송을 우선 확인하세요.</p><h4>해수욕장 마커와 위험 원의 차이</h4><p><b>해수욕장 마커</b>는 대표 위치, 이름과 종합위험도를 표시하며 누르면 요약정보가 나타납니다.</p><p><b>위험 표시 원</b>은 바다에서 주의가 필요한 구역을 나타내며 해수욕장 전체의 위험을 뜻하지 않습니다.</p></div></>}
function Settings(p){const set=(key,value)=>p.setSettings({...p.settings,[key]:value});const layerNames={markers:'해수욕장 마커',names:'해수욕장 이름',risk:'위험 표시 원',rip:'이안류 상태',jelly:'해파리 상태',wave:'파고 상태',surf:'서핑 지수 상태'};return <main className="page"><Header t={p.t} data={p.data}/><section className="hero"><div><small>PREFERENCES</small><h2>{p.t.settings}</h2><p>해담의 이용 방식을 내 환경에 맞게 설정하세요.</p></div></section><section className="card settings"><Setting title="다크 모드" copy="모든 화면의 색상 테마를 변경합니다."><Toggle value={p.settings.dark} onChange={v=>set('dark',v)}/></Setting><div className="favorites"><b>즐겨찾기 관리</b><small>항목을 누르면 해당 해수욕장 상세정보로 이동합니다.</small>{p.favorites.length?<div>{p.favorites.map(id=>{const b=p.data.find(v=>v.id===id);return <button key={id} onClick={()=>p.open(b)}>{b.name}<span onClick={e=>{e.stopPropagation();p.toggle(id)}}>×</span></button>})}</div>:<small>등록한 즐겨찾기가 없습니다.</small>}</div><Setting title="위험 알림" copy="경계 이상 이안류, 해파리 주의보, 높은 파고 등을 배너로 표시합니다."><Toggle value={p.settings.alerts} onChange={v=>set('alerts',v)}/></Setting><Setting title="위치정보 사용" copy="허용하면 현재 위치와 가까운 부산 해수욕장을 추천합니다."><Toggle value={p.settings.location} onChange={v=>set('location',v)}/></Setting><Setting title="언어 / Language" copy="하단 탭과 주요 버튼, 위험도 단계를 실제로 변경합니다."><select value={p.settings.language} onChange={e=>set('language',e.target.value)}><option value="ko">한국어</option><option value="en">English</option></select></Setting><div className="setting stack"><div><b>지도 레이어 설정</b><small>선택을 끄면 지도에서 해당 레이어가 사라집니다.</small></div><div className="layer-grid">{Object.entries(layerNames).map(([key,name])=><label key={key}>{name}<Toggle value={p.settings.layers[key]} onChange={v=>set('layers',{...p.settings.layers,[key]:v})}/></label>)}</div></div><Setting title="서핑 숙련도" copy="결과와 상세 화면의 서핑 추천에 반영됩니다."><select value={p.settings.skill} onChange={e=>set('skill',e.target.value)}><option value="beginner">초급자</option><option value="intermediate">중급자</option><option value="advanced">상급자</option></select></Setting><details open><summary>위험도 색상 안내</summary><Guide/></details><details><summary>서핑 지수 계산 기준</summary><p>파고, 파도 방향, 바람, 수온, 이안류, 입수 통제 상태와 선택한 숙련도를 종합합니다. S 80 이상은 이용 금지이며, S 55~79는 최고 단계가 나쁨을 넘지 않습니다.</p></details><Setting title="자동갱신" copy="현재 상태와 기준 시각을 일정 주기로 갱신합니다."><Toggle value={p.settings.autoRefresh} onChange={v=>set('autoRefresh',v)}/></Setting><button className="setting action" onClick={p.refresh}><span><b>캐시 새로고침</b><small>화면의 현재 상태를 다시 불러옵니다.</small></span>↻</button><button className="setting action reset" onClick={p.reset}><span><b>설정 초기화</b><small>모든 개인 설정과 즐겨찾기를 기본값으로 되돌립니다.</small></span>↺</button><div className="about"><b>해담</b><small>부산 바다의 상태, 안전정보와 이용 정보를 하나의 웹앱에 담은 해양 안전 서비스입니다.</small></div></section></main>}
function Tabs({tab,setTab,t}){return <nav className="tabs">{[['home','⌂'],['risk','!'],['settings','⚙']].map(([id,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{icon}</span>{t[id]}</button>)}</nav>}
function App(){const initial=read('haedam.settings',{});const [settings,setSettings]=useState({...defaults,...initial,layers:{...defaults.layers,...initial.layers}}),[favorites,setFavorites]=useState(()=>read('haedam.favorites',[])),[tab,setTab]=useState(()=>read('haedam.tab','home')),[detail,setDetail]=useState(null),[data,setData]=useState(getMarineData),[toast,setToast]=useState('');const lang=settings.language==='en'?'en':'ko',t=copy[lang];useEffect(()=>{document.body.classList.toggle('dark',settings.dark);store('haedam.settings',settings)},[settings]);useEffect(()=>store('haedam.favorites',favorites),[favorites]);useEffect(()=>store('haedam.tab',tab),[tab]);useEffect(()=>{if(!settings.autoRefresh)return;const i=setInterval(()=>setData(d=>refreshMarineData(d)),30000);return()=>clearInterval(i)},[settings.autoRefresh]);const message=m=>{setToast(m);setTimeout(()=>setToast(''),3400)};const toggle=id=>setFavorites(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);const reset=()=>{if(confirm('모든 설정과 즐겨찾기를 초기화할까요?')){setSettings(defaults);setFavorites([]);localStorage.removeItem('haedam.settings');localStorage.removeItem('haedam.favorites');message('설정이 초기화되었습니다.')}};const refresh=()=>{setData(d=>refreshMarineData(d));message('현재 상태를 새로고침했습니다.')};const p={data,settings,setSettings,favorites,toggle,open:setDetail,t,lang,toast:message,reset,refresh,skillName:settings.skill==='beginner'?'초급자':settings.skill==='intermediate'?'중급자':'상급자'};return <>{toast&&<div className="toast">{toast}<button onClick={()=>setToast('')}>×</button></div>}{detail?<Detail {...p} beach={detail} back={()=>setDetail(null)}/>:<div className="shell">{tab==='home'?<Home {...p}/>:tab==='risk'?<RiskPage {...p}/>:<Settings {...p}/>}<Tabs tab={tab} setTab={setTab} t={t}/></div>}</>}
createRoot(document.getElementById('root')).render(<App/>);
