import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapContainer, Marker, TileLayer, Tooltip, Circle, useMap} from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import './styles.css';

const beaches=[
 ['haeundae','해운대해수욕장','해운대구 우동',35.15870,129.16039,72,1.25,48,18,'노무라입깃해파리',34],
 ['gwangalli','광안리해수욕장','수영구 광안동',35.15317,129.11862,28,.55,22,7,'모니터링 특이사항 없음',18],
 ['songjeong','송정해수욕장','해운대구 송정동',35.17965,129.19953,58,.90,62,13,'보름달물해파리',50],
 ['songdo','송도해수욕장','서구 암남동',35.07639,129.02332,34,.42,31,5,'모니터링 특이사항 없음',25],
 ['dadaepo','다대포해수욕장','사하구 다대동',35.04604,128.96788,84,1.55,78,21,'노무라입깃해파리',0],
 ['ilgwang','일광해수욕장','기장군 일광읍',35.26460,129.23380,51,.72,44,11,'보름달물해파리',36],
 ['imrang','임랑해수욕장','기장군 장안읍',35.32180,129.26390,21,.32,18,4,'모니터링 특이사항 없음',30]
].map(([id,name,area,lat,lng,rip,wave,jelly,reports,species,old])=>({id,name,area,pos:[lat,lng],rip,wave,jelly,reports,species,old}));

const now='2026. 08. 05. 10:00 KST';
const defaults={dark:false,alerts:true,location:false,language:'ko',autoRefresh:true,dataSaver:false,layers:{rip:true,jelly:true,wave:true,surf:true}};
const copy={ko:{home:'홈',risk:'위험도',settings:'설정',detail:'상세 보기',back:'뒤로',favorite:'즐겨찾기',demo:'현재 일부 정보는 해담 웹앱 시연을 위한 예시 데이터입니다.',source:'데이터 출처',refresh:'새로고침',safe:'관심',caution:'주의',alert:'경계',danger:'위험',loading:'데이터 불러오는 중',noDetail:'세부 위험 위치 미제공'},en:{home:'Home',risk:'Risk',settings:'Settings',detail:'View details',back:'Back',favorite:'Favorite',demo:'Some information is demonstration data for the Haedam web app.',source:'Data source',refresh:'Refresh',safe:'Safe',caution:'Caution',alert:'Alert',danger:'Danger',loading:'Loading data',noDetail:'Detailed hazard location unavailable'}};
function read(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}}
const ripLevel=s=>s>=80?'danger':s>=55?'alert':s>=30?'caution':'safe';
const riskLevel=s=>s>=80?'danger':s>=55?'alert':s>=30?'caution':'safe';
function surf(b){if(b.rip>=80)return {score:0,status:'이용 금지',reason:'이안류 위험 단계'}; const wave=b.wave<.3?20:b.wave<.6?50:b.wave<1.2?90:b.wave<1.8?70:b.wave<2.5?40:10;let score=Math.round(wave*.65+(100-b.rip)*.35);if(b.rip>=55)score=Math.min(30,score);return {score,status:score>=70?'좋음':score>=45?'보통':'주의',reason:`파고 ${b.wave.toFixed(2)}m · 이안류 S ${b.rip}`}}
function overall(b){return Math.round(b.rip*.35+Math.min(100,b.jelly*1.3)*.25+Math.min(100,b.wave*45)*.2+(100-surf(b).score)*.2)}
const pin=(l)=>L.divIcon({className:'pin-wrap',html:`<span class="pin ${l}"></span>`,iconSize:[30,30],iconAnchor:[15,30]});
function MapMove({b}){const m=useMap();useEffect(()=>{if(b)m.flyTo(b.pos,14,{duration:.45})},[b,m]);return null}
function BeachMap({selected,onSelect,layers,compact=false}){return <MapContainer className="map" center={selected?.pos||[35.15,129.12]} zoom={selected?14:11} scrollWheelZoom><MapMove b={selected}/><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution="© OpenStreetMap contributors"/>{beaches.map(b=>{let o=overall(b),s=surf(b);return <React.Fragment key={b.id}><Marker position={b.pos} icon={pin(riskLevel(o))} eventHandlers={{click:()=>onSelect?.(b)}}><Tooltip permanent direction="bottom" offset={[0,15]} className="beach-label">{b.name}</Tooltip></Marker>{layers?.rip&&b.rip>=55&&<Circle center={b.pos} radius={0} pathOptions={{opacity:0}}/>}</React.Fragment>})}</MapContainer>}
function Badge({level,score,t}){return <span className={'badge '+level}><i/> {t[level]}{score!==undefined&&` · ${score}`}</span>}
function Toggle({value,onChange,label}){return <button aria-label={label} className={'toggle '+(value?'on':'')} role="switch" aria-checked={value} onClick={()=>onChange(!value)}><i/></button>}
function Favorite({b,favorites,toggle}){let saved=favorites.includes(b.id);return <button className={'favorite '+(saved?'saved':'')} aria-label={saved?'즐겨찾기 삭제':'즐겨찾기 추가'} onClick={()=>toggle(b.id)}>{saved?'★':'☆'}</button>}
function Header({t,onRefresh,refreshing}){return <><header><div className="brand"><span className="brand-mark">⌖</span><div><small>BUSAN OCEAN SAFETY</small><h1>해담</h1></div></div><button className="refresh-button" onClick={onRefresh} aria-label={t.refresh}>{refreshing?'↻': '⟳'} <span>{t.refresh}</span></button></header><div className="meta">부산 해양 안전정보 · {now} · <b className="demo-dot">● 시연용 데이터</b></div></>}
function DataBanner({t}){return <div className="demo-banner">ⓘ {t.demo}<span> 시연용 · 실제 관측값이 아님 · 실제 서비스에서는 공식 API 연결 필요</span></div>}
function Metric({title,value,sub,level}){return <article className="metric"><small>{title}</small><b>{value}</b><span className={level||''}>{sub}</span></article>}
function SafetyCards({b,t,full=false}){const s=surf(b), r=ripLevel(b.rip), o=overall(b), delta=b.old===0?'신규 출현':`${Math.round((b.jelly-b.old)/b.old*100)>0?'+':''}${Math.round((b.jelly-b.old)/b.old*100)}%`;return <div className={full?'card-list':'metric-grid'}>
 <article className="info-card rip"><div className="card-head"><span>↝</span><div><small>이안류 · 최신 공식 지수/예측 연동 필요</small><h3>이안류 S {b.rip}</h3></div><Badge level={r} t={t}/></div><p>{r==='safe'?'발생 가능성이 낮습니다. 현장 안전요원 안내를 따르세요.':r==='caution'?'발생 가능성이 있습니다. 수영 전 안내를 확인하세요.':r==='alert'?'강한 이안류가 예상됩니다. 입수를 자제하세요.':'발생 위험이 매우 높습니다. 바다 수영과 입수를 금합니다.'}</p><footer>시연용 예측값 · 기준시각 {now} · 출처: 국립해양조사원 연계 예정</footer></article>
 <article className="info-card jelly"><div className="card-head"><span>◌</span><div><small>해파리 증가 · 최신 모니터링 정보</small><h3>{b.species}</h3></div><Badge level={b.jelly>=65?'alert':b.jelly>=35?'caution':'safe'} t={t}/></div><p>최근 출현 {b.jelly}건 · 이전 {b.old}건 · {delta} · 신고 {b.reports}건</p><div className="spark">▁▂▃▅▃▆▇</div><footer>시연용 조사자료 · 조사/신고시각 {now} · 출처: 국립수산과학원 연계 예정</footer></article>
 <article className="info-card wave"><div className="card-head"><span>≋</span><div><small>파고 · 최신 관측값/예측값 연동 필요</small><h3>최대 파고 {b.wave.toFixed(2)}m</h3></div><span className="trend">최근 1시간 ↗</span></div><p>24시간 최고 {(b.wave+0.2).toFixed(2)}m · 평균 {Math.max(.1,b.wave-.12).toFixed(2)}m · 최저 {Math.max(.1,b.wave-.3).toFixed(2)}m</p><footer>시연용 예측값 · 관측소: 인근 해양관측소 기준 · {now}</footer></article>
 <article className="info-card surf"><div className="card-head"><span>⌁</span><div><small>서핑 지수 · 해담 자체 계산</small><h3>{s.score}점 · {s.status}</h3></div><Badge level={s.score===0?'danger':s.score<45?'caution':'safe'} t={t}/></div><p>{s.reason} · 초보자 {s.score>=60?'가능':'주의'} / 중급자 {s.score>=45?'가능':'주의'}</p><footer>서핑 지수는 파고와 이안류 등 가용 데이터를 이용해 계산한 해담의 참고용 지수입니다.</footer></article>
 </div>}
function LayerControls({layers,setLayers}){return <div className="layer-controls">{[['rip','이안류'],['jelly','해파리'],['wave','파고 관측소'],['surf','서핑 상태']].map(([id,name])=><label key={id}><input type="checkbox" checked={layers[id]} onChange={e=>setLayers({...layers,[id]:e.target.checked})}/>{name}</label>)}</div>}
function Home({t,settings,setSettings,favorites,toggle,openDetail,notify}){const [selected,setSelected]=useState(beaches[0]);const [refreshing,setRefreshing]=useState(false);const refresh=()=>{setRefreshing(true);setTimeout(()=>setRefreshing(false),650)};const nearby=()=>{if(!settings.location){notify('위치정보 사용을 설정에서 켜면 가장 가까운 해수욕장을 추천합니다.');return}navigator.geolocation?.getCurrentPosition(p=>{let b=beaches.reduce((x,y)=>Math.hypot(x.pos[0]-p.coords.latitude,x.pos[1]-p.coords.longitude)<Math.hypot(y.pos[0]-p.coords.latitude,y.pos[1]-p.coords.longitude)?x:y);setSelected(b);notify(`${b.name}을(를) 가장 가까운 해수욕장으로 추천합니다.`)},()=>notify('위치 권한이 거부되었습니다. 다른 기능은 계속 이용할 수 있습니다.'))};let o=overall(selected);return <main className="page"><Header t={t} onRefresh={refresh} refreshing={refreshing}/><DataBanner t={t}/><section className="home-intro"><div><small>오늘의 부산 바다</small><h2>{selected.name}</h2><p>{selected.area} · 종합 위험도 <b>{o}</b>점</p></div><button className="outline" onClick={nearby}>⌖ 가까운 해수욕장</button></section><section className={'map-box '+(settings.dataSaver?'reduce-motion':'')}><BeachMap selected={selected} onSelect={setSelected} layers={settings.layers}/><LayerControls layers={settings.layers} setLayers={l=>setSettings({...settings,layers:l})}/><p className="map-note">모든 표시는 해수욕장 대표 위치입니다. 위험구역 공간자료가 없어 지도에는 세부 위험 위치를 표시하지 않습니다.</p></section><section className="selection"><div className="selection-title"><div><small>{selected.area}</small><h2>{selected.name}</h2></div><Badge level={riskLevel(o)} score={o} t={t}/><Favorite b={selected} favorites={favorites} toggle={toggle}/></div><div className="quick-metrics"><Metric title="이안류" value={`S ${selected.rip}`} sub={t[ripLevel(selected.rip)]} level={ripLevel(selected.rip)}/><Metric title="해파리" value={`${selected.jelly}건`} sub="최신 모니터링"/><Metric title="파고" value={`${selected.wave.toFixed(2)}m`} sub="시연용 예측값"/><Metric title="서핑 지수" value={`${surf(selected).score}점`} sub={surf(selected).status}/></div><button className="primary wide" onClick={()=>openDetail(selected)}>{t.detail} →</button></section></main>}
function Ranking({t,favorites,toggle,openDetail,onRefresh}){let ranked=useMemo(()=>[...beaches].sort((a,b)=>overall(b)-overall(a)),[]);return <main className="page"><Header t={t} onRefresh={onRefresh}/><DataBanner t={t}/><section className="page-title"><small>BEACH RISK INDEX</small><h2>해수욕장 위험도 순위</h2><p>해담 시연용 가중치: 이안류 35%, 해파리 25%, 파고 20%, 서핑 안전 20%</p></section><div className="ranking">{ranked.map((b,i)=>{let o=overall(b);return <article key={b.id}><button onClick={()=>openDetail(b)}><em>{i+1}</em><div><b>{b.name}</b><small>{b.area} · 시연용 데이터</small><span>이안류 S {b.rip} · 해파리 {b.jelly}건 · 파고 {b.wave.toFixed(2)}m · 서핑 {surf(b).score}점</span></div><strong>{o}</strong><Badge level={riskLevel(o)} t={t}/><i>›</i></button><Favorite b={b} favorites={favorites} toggle={toggle}/></article>})}</div></main>}
function Detail({b,t,favorites,toggle,back,settings}){let o=overall(b);return <main className="detail-page"><div className="detail-header"><button onClick={back} aria-label={t.back}>‹</button><div><small>해담 · BEACH DETAIL</small><h2>{b.name}</h2></div><Badge level={riskLevel(o)} score={o} t={t}/><Favorite b={b} favorites={favorites} toggle={toggle}/></div><section className="detail-map"><BeachMap selected={b} layers={settings.layers}/><p>{t.noDetail} · 해수욕장 대표 위치만 표시</p></section><div className="detail-content"><DataBanner t={t}/><article className="overall"><div><small>해담 시연용 종합 위험도</small><h2>{o}점 · {t[riskLevel(o)]}</h2><p>공식 안전 기준이 아닌 해담의 시연용 가중치 계산값입니다.</p></div><strong>{o}<small>/100</small></strong></article><SafetyCards b={b} t={t} full/><article className="guide"><h3>안전 대처법</h3><p>이안류에 휩쓸리면 해안과 평행한 방향으로 이동하고, 무리하지 말고 구조 요청을 하세요. 긴급 상황은 119에 신고하세요.</p><small>데이터 유형: 시연용 데이터 · 마지막 갱신 {now}</small></article></div></main>}
function Settings({t,settings,setSettings,favorites,toggle,openDetail,notify,reset}){const set=(key,value)=>setSettings({...settings,[key]:value});return <main className="page"><Header t={t} onRefresh={()=>notify('캐시 데이터를 새로고침했습니다.')}/><section className="page-title"><small>PREFERENCES</small><h2>{t.settings}</h2><p>이 기기에만 저장되는 개인 설정입니다.</p></section><section className="settings-list">
 <Row icon="◐" title="다크 모드" text="모든 화면의 밝은/어두운 테마를 변경합니다." right={<Toggle value={settings.dark} onChange={v=>set('dark',v)} label="다크 모드"/>}/>
 <Row icon="★" title="즐겨찾기 해수욕장" text="홈·위험도·상세 화면에서 관리할 수 있습니다."/><div className="favorite-list">{favorites.length?favorites.map(id=>{let b=beaches.find(x=>x.id===id);return <button key={id} onClick={()=>openDetail(b)}>{b.name}<span onClick={e=>{e.stopPropagation();toggle(id)}}>×</span></button>}):<small>즐겨찾는 해수욕장이 없습니다.</small>}</div>
 <Row icon="!" title="해양 위험 알림" text="이안류 경계·위험, 해파리 특보, 높은 파고, 이용 금지를 앱 내부 배너로 알려줍니다." right={<Toggle value={settings.alerts} onChange={v=>set('alerts',v)} label="위험 알림"/>}/>
 <Row icon="⌖" title="위치정보 사용" text="현재 위치에서 가장 가까운 부산 해수욕장을 추천합니다." right={<Toggle value={settings.location} onChange={v=>set('location',v)} label="위치정보"/>}/>
 <div className="row"><span className="row-icon">가</span><div><b>언어 / Language</b><small>메뉴와 주요 안내문을 한국어·영어로 전환합니다.</small></div><select value={settings.language} onChange={e=>set('language',e.target.value)}><option value="ko">한국어</option><option value="en">English</option></select></div>
 <div className="row layers-row"><span className="row-icon">◫</span><div><b>지도 레이어 표시</b><small>이안류, 해파리, 파고 관측소, 서핑 상태의 표시 설정</small><LayerControls layers={settings.layers} setLayers={l=>set('layers',l)}/></div></div>
 <div className="row"><span className="row-icon">↻</span><div><b>데이터 자동갱신</b><small>공식 데이터 제공 주기보다 짧게 요청하지 않습니다.</small></div><Toggle value={settings.autoRefresh} onChange={v=>set('autoRefresh',v)} label="자동갱신"/></div>
 <div className="row"><span className="row-icon">◌</span><div><b>데이터 절약 모드</b><small>자동갱신 빈도를 낮추고 지도 애니메이션을 최소화합니다.</small></div><Toggle value={settings.dataSaver} onChange={v=>set('dataSaver',v)} label="데이터 절약"/></div>
 <Action title="캐시 데이터 새로고침" text="저장된 시연용 데이터를 다시 불러옵니다." onClick={()=>notify('캐시 데이터를 새로고침했습니다.')}/><Action title="데이터 출처" text="국립해양조사원·국립수산과학원·기상청·공공데이터포털 연계 구조" onClick={()=>notify('현재는 API 키 없이 제공되는 시연용 데이터입니다.')}/><Action title="위험도·서핑 지수 계산 기준" text="가중치와 파고 적합 구간은 해담의 참고용 시연 기준입니다." onClick={()=>notify('서핑: 파고 적합도 65% + 이안류 안전도 35%. 이안류 S 80 이상이면 이용 금지.')}/><Action title="설정 초기화" text="저장된 설정을 기본값으로 되돌립니다." danger onClick={reset}/>
 </section></main>}
function Row({icon,title,text,right}){return <div className="row"><span className="row-icon">{icon}</span><div><b>{title}</b><small>{text}</small></div>{right}</div>};function Action({title,text,onClick,danger}) {return <button className={'row action '+(danger?'danger-text':'')} onClick={onClick}><span className="row-icon">›</span><div><b>{title}</b><small>{text}</small></div><i>›</i></button>}
function Tabs({tab,setTab,t}){return <nav className="tabs">{[['home','⌂',t.home],['risk','≋',t.risk],['settings','⚙',t.settings]].map(([id,i,n])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{i}</span>{n}</button>)}</nav>}
function App(){const [settings,setSettings]=useState(()=>({...defaults,...read('haedam.settings',defaults),layers:{...defaults.layers,...read('haedam.settings',defaults).layers}}));const [favorites,setFavorites]=useState(()=>read('haedam.favorites',[]));const [tab,setTab]=useState(()=>read('haedam.tab','home'));const [detail,setDetail]=useState(null);const [notice,setNotice]=useState('');const t=copy[settings.language];useEffect(()=>{document.body.classList.toggle('dark',settings.dark);localStorage.setItem('haedam.settings',JSON.stringify(settings))},[settings]);useEffect(()=>localStorage.setItem('haedam.favorites',JSON.stringify(favorites)),[favorites]);useEffect(()=>localStorage.setItem('haedam.tab',JSON.stringify(tab)),[tab]);useEffect(()=>{if(!settings.alerts)return;let danger=beaches.find(b=>b.rip>=80||surf(b).score===0);if(danger)setNotice(`${danger.name}: 이안류 위험으로 서핑 이용 금지 상태입니다.`)},[settings.alerts]);const toggle=id=>setFavorites(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);const open=b=>setDetail(b);const notify=s=>{setNotice(s);setTimeout(()=>setNotice(''),4500)};const reset=()=>{if(confirm('저장된 해담 설정을 기본값으로 되돌릴까요?')){localStorage.removeItem('haedam.settings');localStorage.removeItem('haedam.favorites');setSettings(defaults);setFavorites([]);notify('설정을 초기화했습니다.')}};return <>{notice&&<div className="notification" role="status">⚠ {notice}<button onClick={()=>setNotice('')}>×</button></div>}{detail?<Detail b={detail} t={t} favorites={favorites} toggle={toggle} back={()=>setDetail(null)} settings={settings}/>:<div className="shell">{tab==='home'&&<Home t={t} settings={settings} setSettings={setSettings} favorites={favorites} toggle={toggle} openDetail={open} notify={notify}/>} {tab==='risk'&&<Ranking t={t} favorites={favorites} toggle={toggle} openDetail={open} onRefresh={()=>notify('시연용 데이터 갱신을 완료했습니다.')}/>} {tab==='settings'&&<Settings t={t} settings={settings} setSettings={setSettings} favorites={favorites} toggle={toggle} openDetail={open} notify={notify} reset={reset}/>}</div>} {!detail&&<Tabs tab={tab} setTab={setTab} t={t}/>}</>};
createRoot(document.getElementById('root')).render(<App/>);
